title: Leonardo Leotte
description: Game Developer
site_title: '@leoleotte - Leonardo Leotte'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: leoleotte
blog_url: https://www.portfolio.leotte.dev
email: leo.leotte@gmail.com
keybase_username: leoleotte
twitter_username: leoleotte
reddit_username: leoleotte

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 